### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anasmohammed361** [anasmohammed361/zenith-mails#4]
- [ ] Email Templates
- [ ] Create Custom Email Templates
- [ ] #5
- [x] Sheet Js Support for custom values
- [ ] Analytics
- [x] SMTP Provider
- [ ] Ability to Post Custom Email Templates
- [ ] Editor Js Support
- [x] Send Attachments
- [x] Limit to 100 Mails
